const questionData = [
    // N5
    { word: "学校", meaning: "School", level: "N5", category: "noun", parts: [{ kanji: "学", reading: "がっ" }, { kanji: "校", reading: "こう" }] },
    { word: "先生", meaning: "Teacher", level: "N5", category: "noun", parts: [{ kanji: "先", reading: "せん" }, { kanji: "生", reading: "せい" }] },
    { word: "学生", meaning: "Student", level: "N5", category: "noun", parts: [{ kanji: "学", reading: "がく" }, { kanji: "生", reading: "せい" }] },
    { word: "大学", meaning: "University", level: "N5", category: "noun", parts: [{ kanji: "大", reading: "だい" }, { kanji: "学", reading: "がく" }] },
    { word: "時間", meaning: "Time", level: "N5", category: "noun", parts: [{ kanji: "時", reading: "じ" }, { kanji: "間", reading: "かん" }] },
    { word: "時計", meaning: "Clock", level: "N5", category: "noun", parts: [{ kanji: "時", reading: "と" }, { kanji: "計", reading: "けい" }] },
    { word: "毎日", meaning: "Every day", level: "N5", category: "noun", parts: [{ kanji: "毎", reading: "まい" }, { kanji: "日", reading: "にち" }] },
    { word: "天気", meaning: "Weather", level: "N5", category: "noun", parts: [{ kanji: "天", reading: "てん" }, { kanji: "気", reading: "き" }] },
    { word: "電車", meaning: "Train", level: "N5", category: "noun", parts: [{ kanji: "電", reading: "でん" }, { kanji: "車", reading: "しゃ" }] },
    { word: "電話", meaning: "Phone", level: "N5", category: "noun", parts: [{ kanji: "電", reading: "でん" }, { kanji: "話", reading: "わ" }] },
    { word: "名前", meaning: "Name", level: "N5", category: "noun", parts: [{ kanji: "名", reading: "な" }, { kanji: "前", reading: "まえ" }] },
    { word: "午前", meaning: "AM", level: "N5", category: "noun", parts: [{ kanji: "午", reading: "ご" }, { kanji: "前", reading: "ぜん" }] },
    { word: "午後", meaning: "PM", level: "N5", category: "noun", parts: [{ kanji: "午", reading: "ご" }, { kanji: "後", reading: "ご" }] },
    { word: "外国", meaning: "Foreign country", level: "N5", category: "noun", parts: [{ kanji: "外", reading: "がい" }, { kanji: "国", reading: "こく" }] },
    { word: "銀行", meaning: "Bank", level: "N5", category: "noun", parts: [{ kanji: "銀", reading: "ぎん" }, { kanji: "行", reading: "こう" }] },
    { word: "会社", meaning: "Company", level: "N5", category: "noun", parts: [{ kanji: "会", reading: "かい" }, { kanji: "社", reading: "しゃ" }] },
    { word: "新聞", meaning: "Newspaper", level: "N5", category: "noun", parts: [{ kanji: "新", reading: "しん" }, { kanji: "聞", reading: "ぶん" }] },
    { word: "木曜日", meaning: "Thursday", level: "N5", category: "noun", parts: [{ kanji: "木", reading: "もく" }, { kanji: "曜", reading: "よう" }, { kanji: "日", reading: "び" }] },
    { word: "金曜日", meaning: "Friday", level: "N5", category: "noun", parts: [{ kanji: "金", reading: "きん" }, { kanji: "曜", reading: "よう" }, { kanji: "日", reading: "び" }] },

    // N4
    { word: "家族", meaning: "Family", level: "N4", category: "noun", parts: [{ kanji: "家", reading: "か" }, { kanji: "族", reading: "ぞく" }] },
    { word: "意見", meaning: "Opinion", level: "N4", category: "noun", parts: [{ kanji: "意", reading: "い" }, { kanji: "見", reading: "けん" }] },
    { word: "準備", meaning: "Preparation", level: "N4", category: "verb", parts: [{ kanji: "準", reading: "じゅん" }, { kanji: "備", reading: "び" }] },
    { word: "経験", meaning: "Experience", level: "N4", category: "verb", parts: [{ kanji: "経", reading: "けい" }, { kanji: "験", reading: "けん" }] },
    { word: "理由", meaning: "Reason", level: "N4", category: "noun", parts: [{ kanji: "理", reading: "り" }, { kanji: "由", reading: "ゆう" }] },
    { word: "経済", meaning: "Economy", level: "N4", category: "noun", parts: [{ kanji: "経", reading: "けい" }, { kanji: "済", reading: "ざい" }] },
    { word: "政治", meaning: "Politics", level: "N4", category: "noun", parts: [{ kanji: "政", reading: "せい" }, { kanji: "治", reading: "じ" }] },
    { word: "社会", meaning: "Society", level: "N4", category: "noun", parts: [{ kanji: "社", reading: "しゃ" }, { kanji: "会", reading: "かい" }] },
    { word: "研究", meaning: "Research", level: "N4", category: "verb", parts: [{ kanji: "研", reading: "けん" }, { kanji: "究", reading: "きゅう" }] },
    { word: "質問", meaning: "Question", level: "N4", category: "verb", parts: [{ kanji: "質", reading: "しつ" }, { kanji: "問", reading: "もん" }] },
    { word: "問題", meaning: "Problem", level: "N4", category: "noun", parts: [{ kanji: "問", reading: "もん" }, { kanji: "題", reading: "だい" }] },
    { word: "注意", meaning: "Caution", level: "N4", category: "verb", parts: [{ kanji: "注", reading: "ちゅう" }, { kanji: "意", reading: "い" }] },
    { word: "意味", meaning: "Meaning", level: "N4", category: "noun", parts: [{ kanji: "意", reading: "い" }, { kanji: "味", reading: "み" }] },
    { word: "趣味", meaning: "Hobby", level: "N4", category: "noun", parts: [{ kanji: "趣", reading: "しゅ" }, { kanji: "味", reading: "み" }] },
    { word: "興味", meaning: "Interest", level: "N4", category: "noun", parts: [{ kanji: "興", reading: "きょう" }, { kanji: "味", reading: "み" }] },

    // N3
    { word: "感情", meaning: "Emotion", level: "N3", category: "noun", parts: [{ kanji: "感", reading: "かん" }, { kanji: "情", reading: "じょう" }] },
    { word: "愛情", meaning: "Love", level: "N3", category: "noun", parts: [{ kanji: "愛", reading: "あい" }, { kanji: "情", reading: "じょう" }] },
    { word: "信用", meaning: "Trust", level: "N3", category: "verb", parts: [{ kanji: "信", reading: "しん" }, { kanji: "用", reading: "よう" }] },
    { word: "夢想", meaning: "Daydream", level: "N3", category: "verb", parts: [{ kanji: "夢", reading: "む" }, { kanji: "想", reading: "そう" }] },
    { word: "景色", meaning: "Scenery", level: "N3", category: "noun", parts: [{ kanji: "景", reading: "けい" }, { kanji: "色", reading: "しょく" }] },
    { word: "音声", meaning: "Audio", level: "N3", category: "noun", parts: [{ kanji: "音", reading: "おん" }, { kanji: "声", reading: "せい" }] },
    { word: "努力", meaning: "Effort", level: "N3", category: "verb", parts: [{ kanji: "努", reading: "ど" }, { kanji: "力", reading: "りょく" }] },
    { word: "生命", meaning: "Life", level: "N3", category: "noun", parts: [{ kanji: "生", reading: "せい" }, { kanji: "命", reading: "めい" }] },
    { word: "神経", meaning: "Nerve", level: "N3", category: "noun", parts: [{ kanji: "神", reading: "しん" }, { kanji: "経", reading: "けい" }] },
    { word: "世界", meaning: "World", level: "N3", category: "noun", parts: [{ kanji: "世", reading: "せ" }, { kanji: "界", reading: "かい" }] },
    { word: "平和", meaning: "Peace", level: "N3", category: "adjective", parts: [{ kanji: "平", reading: "へい" }, { kanji: "和", reading: "わ" }] },
    { word: "自由", meaning: "Freedom", level: "N3", category: "adjective", parts: [{ kanji: "自", reading: "じ" }, { kanji: "由", reading: "ゆう" }] },
    { word: "希望", meaning: "Hope", level: "N3", category: "verb", parts: [{ kanji: "希", reading: "き" }, { kanji: "望", reading: "ぼう" }] },
    { word: "約束", meaning: "Promise", level: "N3", category: "verb", parts: [{ kanji: "約", reading: "やく" }, { kanji: "束", reading: "そく" }] },
    { word: "規則", meaning: "Rule", level: "N3", category: "noun", parts: [{ kanji: "規", reading: "き" }, { kanji: "則", reading: "そく" }] },

    // N2
    { word: "哲学", meaning: "Philosophy", level: "N2", category: "noun", parts: [{ kanji: "哲", reading: "てつ" }, { kanji: "学", reading: "がく" }] },
    { word: "芸術", meaning: "Art", level: "N2", category: "noun", parts: [{ kanji: "芸", reading: "げい" }, { kanji: "術", reading: "じゅつ" }] },
    { word: "科学", meaning: "Science", level: "N2", category: "noun", parts: [{ kanji: "科", reading: "か" }, { kanji: "学", reading: "がく" }] },
    { word: "技術", meaning: "Technology", level: "N2", category: "noun", parts: [{ kanji: "技", reading: "ぎ" }, { kanji: "術", reading: "じゅつ" }] },
    { word: "環境", meaning: "Environment", level: "N2", category: "noun", parts: [{ kanji: "環", reading: "かん" }, { kanji: "境", reading: "きょう" }] },
    { word: "宇宙", meaning: "Universe", level: "N2", category: "noun", parts: [{ kanji: "宇", reading: "う" }, { kanji: "宙", reading: "ちゅう" }] },
    { word: "意識", meaning: "Consciousness", level: "N2", category: "noun", parts: [{ kanji: "意", reading: "い" }, { kanji: "識", reading: "しき" }] },
    { word: "記憶", meaning: "Memory", level: "N2", category: "verb", parts: [{ kanji: "記", reading: "き" }, { kanji: "憶", reading: "おく" }] },
    { word: "思考", meaning: "Thought", level: "N2", category: "verb", parts: [{ kanji: "思", reading: "し" }, { kanji: "考", reading: "こう" }] },
    { word: "想像", meaning: "Imagination", level: "N2", category: "verb", parts: [{ kanji: "想", reading: "そう" }, { kanji: "像", reading: "ぞう" }] },
    { word: "創造", meaning: "Creation", level: "N2", category: "verb", parts: [{ kanji: "創", reading: "そう" }, { kanji: "造", reading: "ぞう" }] },
    { word: "破壊", meaning: "Destruction", level: "N2", category: "verb", parts: [{ kanji: "破", reading: "は" }, { kanji: "壊", reading: "かい" }] },
    { word: "復興", meaning: "Reconstruction", level: "N2", category: "verb", parts: [{ kanji: "復", reading: "ふっ" }, { kanji: "興", reading: "こう" }] },
    { word: "絶対", meaning: "Absolutely", level: "N2", category: "adjective", parts: [{ kanji: "絶", reading: "ぜっ" }, { kanji: "対", reading: "たい" }] },
    { word: "複雑", meaning: "Complex", level: "N2", category: "adjective", parts: [{ kanji: "複", reading: "ふく" }, { kanji: "雑", reading: "ざつ" }] },

    // N1
    { word: "鬱病", meaning: "Depression", level: "N1", category: "noun", parts: [{ kanji: "鬱", reading: "うつ" }, { kanji: "病", reading: "びょう" }] },
    { word: "薔薇", meaning: "Rose", level: "N1", category: "noun", parts: [{ kanji: "薔", reading: "ば" }, { kanji: "薇", reading: "ら" }] },
    { word: "躊躇", meaning: "Hesitation", level: "N1", category: "verb", parts: [{ kanji: "躊", reading: "ちゅう" }, { kanji: "躇", reading: "ちょ" }] },
    { word: "完璧", meaning: "Perfect", level: "N1", category: "adjective", parts: [{ kanji: "完", reading: "かん" }, { kanji: "璧", reading: "ぺき" }] },
    { word: "挨拶", meaning: "Greeting", level: "N1", category: "verb", parts: [{ kanji: "挨", reading: "あい" }, { kanji: "拶", reading: "さつ" }] },
    { word: "嫉妬", meaning: "Jealousy", level: "N1", category: "verb", parts: [{ kanji: "嫉", reading: "しっ" }, { kanji: "妬", reading: "と" }] },
    { word: "曖昧", meaning: "Ambiguous", level: "N1", category: "adjective", parts: [{ kanji: "曖", reading: "あい" }, { kanji: "昧", reading: "まい" }] },
    { word: "葛藤", meaning: "Conflict", level: "N1", category: "verb", parts: [{ kanji: "葛", reading: "かっ" }, { kanji: "藤", reading: "とう" }] },
    { word: "傲慢", meaning: "Arrogance", level: "N1", category: "adjective", parts: [{ kanji: "傲", reading: "ごう" }, { kanji: "慢", reading: "まん" }] },
    { word: "謙虚", meaning: "Modesty", level: "N1", category: "adjective", parts: [{ kanji: "謙", reading: "けん" }, { kanji: "虚", reading: "きょ" }] },
    { word: "真摯", meaning: "Sincere", level: "N1", category: "adjective", parts: [{ kanji: "真", reading: "しん" }, { kanji: "摯", reading: "し" }] },
    { word: "貪欲", meaning: "Greed", level: "N1", category: "adjective", parts: [{ kanji: "貪", reading: "どん" }, { kanji: "欲", reading: "よく" }] },
    { word: "堕落", meaning: "Corruption", level: "N1", category: "verb", parts: [{ kanji: "堕", reading: "だ" }, { kanji: "落", reading: "らく" }] },
    { word: "孤高", meaning: "Aloof", level: "N1", category: "adjective", parts: [{ kanji: "孤", reading: "こ" }, { kanji: "高", reading: "こう" }] },
    { word: "崇高", meaning: "Sublime", level: "N1", category: "adjective", parts: [{ kanji: "崇", reading: "すう" }, { kanji: "高", reading: "こう" }] },
    { word: "神聖", meaning: "Sacred", level: "N1", category: "adjective", parts: [{ kanji: "神", reading: "しん" }, { kanji: "聖", reading: "せい" }] },
    { word: "冒涜", meaning: "Blasphemy", level: "N1", category: "verb", parts: [{ kanji: "冒", reading: "ぼう" }, { kanji: "涜", reading: "とく" }] },
    { word: "奇跡", meaning: "Miracle", level: "N1", category: "noun", parts: [{ kanji: "奇", reading: "き" }, { kanji: "跡", reading: "せき" }] },
    { word: "運命", meaning: "Fate", level: "N1", category: "noun", parts: [{ kanji: "運", reading: "うん" }, { kanji: "命", reading: "めい" }] },
    { word: "永遠", meaning: "Eternity", level: "N1", category: "noun", parts: [{ kanji: "永", reading: "えい" }, { kanji: "遠", reading: "えん" }] }
];

const kanjiDictionary = {
    "学": { onyomi: "ガク (gaku)", kunyomi: "まな.ぶ (mana.bu)", meaning: "Study, learning" },
    "校": { onyomi: "コウ (kou)", kunyomi: "-", meaning: "School" },
    "先": { onyomi: "セン (sen)", kunyomi: "さき (saki)", meaning: "Before, ahead" },
    "生": { onyomi: "セイ (sei), ショウ (shou)", kunyomi: "い.きる (i.kiru), う.む (u.mu)", meaning: "Life, genuine, birth" },
    "大": { onyomi: "ダイ (dai), タイ (tai)", kunyomi: "おお.きい (oo.kii)", meaning: "Large, big" },
    "時": { onyomi: "ジ (ji)", kunyomi: "とき (toki)", meaning: "Time, hour" },
    "間": { onyomi: "カン (kan), ケン (ken)", kunyomi: "あいだ (aida), ま (ma)", meaning: "Interval, space" },
    "計": { onyomi: "ケイ (kei)", kunyomi: "はか.る (haka.ru)", meaning: "Plot, plan, scheme" },
    "毎": { onyomi: "マイ (mai)", kunyomi: "ごと (goto)", meaning: "Every" },
    "日": { onyomi: "ニチ (nichi), ジツ (jitsu)", kunyomi: "ひ (hi), -び (-bi)", meaning: "Day, sun" },
    "天": { onyomi: "テン (ten)", kunyomi: "あまつ (amatsu)", meaning: "Heavens, sky" },
    "気": { onyomi: "キ (ki), ケ (ke)", kunyomi: "いき (iki)", meaning: "Spirit, mind, air" },
    "電": { onyomi: "デン (den)", kunyomi: "-", meaning: "Electricity" },
    "車": { onyomi: "シャ (sha)", kunyomi: "くるま (kuruma)", meaning: "Car, wheel" },
    "話": { onyomi: "ワ (wa)", kunyomi: "はな.す (hana.su), はなし (hanashi)", meaning: "Tale, talk" },
    "名": { onyomi: "メイ (mei), ミョウ (myou)", kunyomi: "な (na)", meaning: "Name, noted" },
    "前": { onyomi: "ゼン (zen)", kunyomi: "まえ (mae)", meaning: "In front, before" },
    "午": { onyomi: "ゴ (go)", kunyomi: "うま (uma)", meaning: "Noon, sign of the horse" },
    "後": { onyomi: "ゴ (go), コウ (kou)", kunyomi: "のち (nochi), うし.ろ (ushi.ro), あと (ato)", meaning: "Behind, back, later" },
    "外": { onyomi: "ガイ (gai), ゲ (ge)", kunyomi: "そと (soto), ほか (hoka), はず.す (hazu.su)", meaning: "Outside" },
    "国": { onyomi: "コク (koku)", kunyomi: "くに (kuni)", meaning: "Country" },
    "銀": { onyomi: "ギン (gin)", kunyomi: "しろがね (shirogane)", meaning: "Silver" },
    "行": { onyomi: "コウ (kou), ギョウ (gyou)", kunyomi: "い.く (i.ku), ゆ.く (yu.ku), おこな.う (okona.u)", meaning: "Going, journey" },
    "会": { onyomi: "カイ (kai), エ (e)", kunyomi: "あ.う (a.u)", meaning: "Meeting, meet" },
    "社": { onyomi: "シャ (sha)", kunyomi: "やしろ (yashiro)", meaning: "Company, firm, office, shrine" },
    "新": { onyomi: "シン (shin)", kunyomi: "あたら.しい (atara.shii), あら.た (ara.ta)", meaning: "New" },
    "聞": { onyomi: "ブン (bun), モン (mon)", kunyomi: "き.く (ki.ku), き.こえる (ki.koeru)", meaning: "Hear, ask, listen" },
    "木": { onyomi: "ボク (boku), モク (moku)", kunyomi: "き (ki)", meaning: "Tree, wood" },
    "曜": { onyomi: "ヨウ (you)", kunyomi: "-", meaning: "Weekday" },
    "金": { onyomi: "キン (kin), コン (kon), ゴン (gon)", kunyomi: "かね (kane), かな- (kana-)", meaning: "Gold, metal, money" },

    "家": { onyomi: "カ (ka), ケ (ke)", kunyomi: "いえ (ie), や (ya)", meaning: "House, home, family" },
    "族": { onyomi: "ゾク (zoku)", kunyomi: "-", meaning: "Tribe, family" },
    "意": { onyomi: "イ (i)", kunyomi: "-", meaning: "Idea, mind, heart, taste, thought" },
    "見": { onyomi: "ケン (ken)", kunyomi: "み.る (mi.ru), み.える (mi.eru), み.せる (mi.seru)", meaning: "See, hopes, chances, idea, opinion" },
    "準": { onyomi: "ジュン (jun)", kunyomi: "じゅん.じる (jun.jiru)", meaning: "Semi-, correspond to, proportionate to" },
    "備": { onyomi: "ビ (bi)", kunyomi: "そな.える (sona.eru), そな.わる (sona.waru)", meaning: "Equip, provision, preparation" },
    "経": { onyomi: "ケイ (kei), キョウ (kyou)", kunyomi: "へ.る (he.ru), た.つ (ta.tsu)", meaning: "Sutra, longitude, pass thru, manage" },
    "験": { onyomi: "ケン (ken), ゲン (gen)", kunyomi: "あかし (akashi), しるし (shirushi), ため.す (tame.su)", meaning: "Verification, effect, testing" },
    "理": { onyomi: "リ (ri)", kunyomi: "-", meaning: "Logic, arrangement, reason, justice" },
    "由": { onyomi: "ユ (yu), ユウ (yuu), ユイ (yui)", kunyomi: "よし (yoshi), よ.る (yo.ru)", meaning: "Wherefore, a reason" },
    "済": { onyomi: "サイ (sai), セイ (sei)", kunyomi: "す.む (su.mu), す.ます (su.masu)", meaning: "Settle, relieve, finish" },
    "政": { onyomi: "セイ (sei), ショウ (shou)", kunyomi: "まつりごと (matsurigoto)", meaning: "Politics, government" },
    "治": { onyomi: "ジ (ji), チ (chi)", kunyomi: "おさ.める (osa.meru), なお.る (nao.ru)", meaning: "Reign, cure, heal" },
    "研": { onyomi: "ケン (ken)", kunyomi: "と.ぐ (to.gu)", meaning: "Polish, study of, sharpen" },
    "究": { onyomi: "キュウ (kyuu)", kunyomi: "きわ.める (kiwa.meru)", meaning: "Research, study" },
    "質": { onyomi: "シツ (shitsu), シチ (shichi), チ (chi)", kunyomi: "たち (tachi), ただ.す (tada.su)", meaning: "Substance, quality, matter" },
    "問": { onyomi: "モン (mon)", kunyomi: "と.う (to.u), とん (ton)", meaning: "Question, ask, problem" },
    "題": { onyomi: "ダイ (dai)", kunyomi: "-", meaning: "Topic, subject" },
    "注": { onyomi: "チュウ (chuu)", kunyomi: "そそ.ぐ (soso.gu), さ.す (sa.su)", meaning: "Pour, irrigate, shed (tears), flow into, concentrate on" },
    "趣": { onyomi: "シュ (shu)", kunyomi: "おもむき (omomuki)", meaning: "Gist, proceed to, tend, become" },
    "興": { onyomi: "コウ (kou), キョウ (kyou)", kunyomi: "おこ.る (oko.ru), おこ.す (oko.su)", meaning: "Entertain, revive, retrieve, interest, pleasure" },
    "味": { onyomi: "ミ (mi)", kunyomi: "あじ (aji), あじ.わう (aji.wau)", meaning: "Flavor, taste" },

    "感": { onyomi: "カン (kan)", kunyomi: "-", meaning: "Emotion, feeling, sensation" },
    "情": { onyomi: "ジョウ (jou), セイ (sei)", kunyomi: "なさ.け (nasa.ke)", meaning: "Feelings, emotion, passion, sympathy" },
    "愛": { onyomi: "アイ (ai)", kunyomi: "いと.おしい (ito.oshii)", meaning: "Love, affection" },
    "信": { onyomi: "シン (shin)", kunyomi: "-", meaning: "Faith, truth, fidelity, trust" },
    "用": { onyomi: "ヨウ (you)", kunyomi: "もち.いる (mochi.iru)", meaning: "Utilize, business, service, use, employ" },
    "夢": { onyomi: "ム (mu)", kunyomi: "ゆめ (yume)", meaning: "Dream, vision, illusion" },
    "想": { onyomi: "ソウ (sou), ソ (so)", kunyomi: "おも.う (omo.u)", meaning: "Concept, think, idea, thought" },
    "景": { onyomi: "ケイ (kei)", kunyomi: "-", meaning: "Scenery, view" },
    "色": { onyomi: "ショク (shoku), シキ (shiki)", kunyomi: "いろ (iro)", meaning: "Color" },
    "音": { onyomi: "オン (on), イン (in)", kunyomi: "おと (oto), ね (ne)", meaning: "Sound, noise" },
    "声": { onyomi: "セイ (sei), ショウ (shou)", kunyomi: "こえ (koe), こわ- (kowa-)", meaning: "Voice" },
    "努": { onyomi: "ド (do)", kunyomi: "つと.める (tsuto.meru)", meaning: "Toil, diligent, as much as possible" },
    "力": { onyomi: "リョク (ryoku), リキ (riki)", kunyomi: "ちから (chikara)", meaning: "Power, strength, exert" },
    "命": { onyomi: "メイ (mei), ミョウ (myou)", kunyomi: "いのち (inochi)", meaning: "Fate, command, decree, destiny, life" },
    "神": { onyomi: "シン (shin), ジン (jin)", kunyomi: "かみ (kami), かん- (kan-), こう- (kou-)", meaning: "Gods, mind, soul" },
    "世": { onyomi: "セイ (sei), セ (se)", kunyomi: "よ (yo)", meaning: "Generation, world, society, public" },
    "界": { onyomi: "カイ (kai)", kunyomi: "-", meaning: "World, boundary" },
    "平": { onyomi: "ヘイ (hei), ビョウ (byou)", kunyomi: "たい.ら (tai.ra), ひら (hira)", meaning: "Even, flat, peace" },
    "和": { onyomi: "ワ (wa), オ (o), カ (ka)", kunyomi: "やわ.らぐ (yawa.ragu), なご.む (nago.mu)", meaning: "Harmony, Japanese style, peace" },
    "自": { onyomi: "ジ (ji), シ (shi)", kunyomi: "みずか.ら (mizuka.ra), おの.ずから (ono.zukara)", meaning: "Oneself" },
    "希": { onyomi: "キ (ki), ケ (ke)", kunyomi: "まれ (mare)", meaning: "Hope, beg, request, rare" },
    "望": { onyomi: "ボウ (bou), モウ (mou)", kunyomi: "のぞ.む (nozo.mu)", meaning: "Ambition, full moon, hope, desire, expect" },
    "約": { onyomi: "ヤク (yaku)", kunyomi: "つづ.まる (tsudu.maru)", meaning: "Promise, approximately, shrink" },
    "束": { onyomi: "ソク (soku)", kunyomi: "たば (taba), つか (tsuka)", meaning: "Bundle, sheaf, ream, tie in bundles" },
    "規": { onyomi: "キ (ki)", kunyomi: "-", meaning: "Standard, measure" },
    "則": { onyomi: "ソク (soku)", kunyomi: "のっと.る (notto.ru)", meaning: "Rule, follow, based on, model after" },

    "哲": { onyomi: "テツ (tetsu)", kunyomi: "-", meaning: "Philosophy, clear" },
    "芸": { onyomi: "ゲイ (gei)", kunyomi: "う.える (u.eru), のり (nori), わざ (waza)", meaning: "Technique, art, craft, performance" },
    "術": { onyomi: "ジュツ (jutsu)", kunyomi: "すべ (sube)", meaning: "Art, technique, skill, means, trick" },
    "科": { onyomi: "カ (ka)", kunyomi: "-", meaning: "Department, course, section" },
    "技": { onyomi: "ギ (gi)", kunyomi: "わざ (waza)", meaning: "Skill, art, craft, ability, feat, performance" },
    "環": { onyomi: "カン (kan)", kunyomi: "わ (wa)", meaning: "Ring, circle, link, wheel" },
    "境": { onyomi: "キョウ (kyou), ケイ (kei)", kunyomi: "さかい (sakai)", meaning: "Boundary, border, region" },
    "宇": { onyomi: "ウ (u)", kunyomi: "-", meaning: "Eaves, roof, house, heaven" },
    "宙": { onyomi: "チュウ (chuu)", kunyomi: "-", meaning: "Mid-air, air, space, sky, memorization" },
    "識": { onyomi: "シキ (shiki)", kunyomi: "-", meaning: "Discriminating, know, write" },
    "記": { onyomi: "キ (ki)", kunyomi: "しる.す (shiru.su)", meaning: "Scribe, account, narrative" },
    "憶": { onyomi: "オク (oku)", kunyomi: "-", meaning: "Recollection, think, remember" },
    "思": { onyomi: "シ (shi)", kunyomi: "おも.う (omo.u)", meaning: "Think" },
    "考": { onyomi: "コウ (kou)", kunyomi: "かんが.える (kanga.eru)", meaning: "Consider, think over" },
    "像": { onyomi: "ゾウ (zou)", kunyomi: "-", meaning: "Statue, picture, image, figure, portrait" },
    "創": { onyomi: "ソウ (sou), ショウ (shou)", kunyomi: "つく.る (tsuku.ru), はじ.める (haji.meru), きず (kizu)", meaning: "Genesis, wound, injury, creation" },
    "造": { onyomi: "ゾウ (zou)", kunyomi: "つく.る (tsuku.ru)", meaning: "Create, make, structure, physique" },
    "破": { onyomi: "ハ (ha)", kunyomi: "やぶ.る (yabu.ru)", meaning: "Rend, rip, tear, break, destroy" },
    "壊": { onyomi: "カイ (kai), エ (e)", kunyomi: "こわ.す (kowa.su)", meaning: "Demolition, break, destroy" },
    "復": { onyomi: "フク (fuku)", kunyomi: "また (mata)", meaning: "Restore, return to, revert, resume" },
    "絶": { onyomi: "ゼツ (zetsu)", kunyomi: "た.える (ta.eru), た.つ (ta.tsu)", meaning: "Sever, cut off, disconnect, absolute" },
    "対": { onyomi: "タイ (tai), ツイ (tsui)", kunyomi: "あいて (aite), こた.える (kota.eru)", meaning: "Vis-a-vis, opposite, even, equal, versus" },
    "複": { onyomi: "フク (fuku)", kunyomi: "-", meaning: "Duplicate, double, compound, multiple" },
    "雑": { onyomi: "ザツ (zatsu), ゾウ (zou)", kunyomi: "まじ.える (maji.eru), まじ.る (maji.ru)", meaning: "Miscellaneous" },

    "鬱": { onyomi: "ウツ (utsu)", kunyomi: "ふさ.ぐ (fusa.gu), しげ.る (shige.ru)", meaning: "Gloom, depression, melancholy" },
    "病": { onyomi: "ビョウ (byou), ヘイ (hei)", kunyomi: "やむ (yamu), やまい (yamai)", meaning: "Ill, sick" },
    "薔": { onyomi: "ショウ (shou), ソウ (sou)", kunyomi: "みずたで (mizutade)", meaning: "Rose" },
    "薇": { onyomi: "ビ (bi)", kunyomi: "ぜんまい (zenmai)", meaning: "Fern, rose" },
    "躊": { onyomi: "チュウ (chuu)", kunyomi: "ためら.う (tamera.u)", meaning: "Hesitate" },
    "躇": { onyomi: "チョ (cho)", kunyomi: "ためら.う (tamera.u)", meaning: "Hesitate" },
    "完": { onyomi: "カン (kan)", kunyomi: "-", meaning: "Perfect, completion, end" },
    "璧": { onyomi: "ヘキ (heki)", kunyomi: "-", meaning: "Sphere, ball" },
    "挨": { onyomi: "アイ (ai)", kunyomi: "ひら.く (hira.ku)", meaning: "Push open" },
    "拶": { onyomi: "サツ (satsu)", kunyomi: "せま.る (sema.ru)", meaning: "Imminent" },
    "嫉": { onyomi: "シツ (shitsu)", kunyomi: "ねた.む (neta.mu), そね.む (sone.mu)", meaning: "Jealous, envy" },
    "妬": { onyomi: "ト (to)", kunyomi: "ねた.む (neta.mu), そね.む (sone.mu)", meaning: "Jealous, envy" },
    "曖": { onyomi: "アイ (ai)", kunyomi: "くら.い (kura.i)", meaning: "Dark, not clear" },
    "昧": { onyomi: "マイ (mai), バツ (batsu)", kunyomi: "くら.い (kura.i)", meaning: "Dark, foolish" },
    "葛": { onyomi: "カツ (katsu)", kunyomi: "くず (kuzu), つづら (tsudura)", meaning: "Arrowroot, kudzu" },
    "藤": { onyomi: "トウ (tou)", kunyomi: "ふじ (fuji)", meaning: "Wisteria" },
    "傲": { onyomi: "ゴウ (gou)", kunyomi: "おご.る (ogo.ru), あなど.る (anado.ru)", meaning: "Proud, haughty, arrogant" },
    "慢": { onyomi: "マン (man)", kunyomi: "おこた.る (okota.ru)", meaning: "Ridicule, laziness" },
    "謙": { onyomi: "ケン (ken)", kunyomi: "-", meaning: "Self-depreciating, condescend" },
    "虚": { onyomi: "キョ (kyo), コ (ko)", kunyomi: "むな.しい (muna.shii), うつ.ろ (utsu.ro)", meaning: "Void, emptiness, unpreparedness" },
    "真": { onyomi: "シン (shin)", kunyomi: "ま (ma), まこと (makoto)", meaning: "True, reality" },
    "摯": { onyomi: "シ (shi)", kunyomi: "と.る (to.ru)", meaning: "Gift, serious" },
    "貪": { onyomi: "ドン (don), トン (ton)", kunyomi: "むさぼ.る (musabo.ru)", meaning: "Covet, indulge in" },
    "欲": { onyomi: "ヨク (yoku)", kunyomi: "ほっ.する (hos.suru), ほ.しい (ho.shii)", meaning: "Longing, covetousness, greed, passion" },
    "堕": { onyomi: "ダ (da)", kunyomi: "お.ちる (o.chiru), くず.す (kuzu.su)", meaning: "Degenerate, descend to, lapse into" },
    "落": { onyomi: "ラク (raku)", kunyomi: "お.ちる (o.chiru), お.とす (o.tosu)", meaning: "Fall, drop, come down" },
    "孤": { onyomi: "コ (ko)", kunyomi: "-", meaning: "Orphan, alone" },
    "高": { onyomi: "コウ (kou)", kunyomi: "たか.い (taka.i), たか (taka)", meaning: "Tall, high, expensive" },
    "崇": { onyomi: "スウ (suu)", kunyomi: "あが.める (aga.meru)", meaning: "Adore, respect, revere, worship" },
    "聖": { onyomi: "セイ (sei), ショウ (shou)", kunyomi: "ひじり (hijiri)", meaning: "Holy, saint, sage, master, priest" },
    "冒": { onyomi: "ボウ (bou)", kunyomi: "おか.す (oka.su)", meaning: "Risk, face, defy, dare, damage, desecrate" },
    "涜": { onyomi: "トク (toku)", kunyomi: "けが.す (kega.su)", meaning: "Defile, defame, blasphemy" },
    "奇": { onyomi: "キ (ki)", kunyomi: "く.しき (ku.shiki), あや.しい (aya.shii)", meaning: "Strange, strangeness, curiosity" },
    "跡": { onyomi: "セキ (seki)", kunyomi: "あと (ato)", meaning: "Tracks, mark, print, impression" },
    "運": { onyomi: "ウン (un)", kunyomi: "はこ.ぶ (hako.bu)", meaning: "Carry, luck, destiny, fate" },
    "永": { onyomi: "エイ (ei)", kunyomi: "なが.い (naga.i)", meaning: "Eternity, long, lengthy" },
    "遠": { onyomi: "エン (en), オン (on)", kunyomi: "とお.い (too.i)", meaning: "Distant, far" }
};
